In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
from time import sleep
import requests
import json
import re
from selenium.common.exceptions import NoSuchElementException
import csv
import pandas as pd
import os
from urllib.request import urlopen

In [2]:
driver = webdriver.Chrome('./chromedriver')
driver.implicitly_wait(2)
#상품소개-간편식사-전체 에서 시작
driver.get('https://cu.bgfretail.com/product/product.do?category=product&depth2=4')

In [46]:
#특정 대분류가 있다면
for index in range(7,8):   
    bigNum = index
    bigNumString = 10*bigNum
    tempForBigGroup = "gomaincategory('"+str(bigNumString)+"',"+str(bigNum)+")"
#while html.find(tempForBigGroup)!=-1:
    #대분류 클릭
    driver.execute_script(tempForBigGroup)
    driver.implicitly_wait(2)
    
    html = driver.page_source
    soup = BeautifulSoup(html, "lxml")
    
    #페이지 더보기 계속 클릭
    exist = True
    for i in range(70):
        try:
            driver.execute_script("script:nextPage(1);")
            #driver.implicitly_wait(30+i*30)
        except:
            print("not found")
            exist = False
        if not exist:
            break;
    
    html = driver.page_source
    soup = BeautifulSoup(html, "lxml")

In [47]:
html = driver.page_source
soup = BeautifulSoup(html, "lxml")
item_images = soup.select('div[class=prodListWrap] > ul > li > div[class="photo"] > a > img')
item_names = soup.select('div[class="prodListWrap"] > ul > li > p[class="prodName"] > span')
bigGroup = soup.select('h1')

result = []
for i in range(len(item_names)):
    item_dict = {}
    item_dict['category'] = bigGroup[0].text.strip()
    item_dict['item_name'] = item_names[i].text
    item_dict['img_src'] = item_images[i]['src']
    result.append(item_dict)
    print(item_dict)

{'category': '생활용품', 'item_name': '코엘)가정용충전아답터', 'img_src': 'http://bgf-cu.xcache.kinxcdn.com/product/8809182006358.jpg'}
{'category': '생활용품', 'item_name': '씨앤)아이리버블랙', 'img_src': 'http://bgf-cu.xcache.kinxcdn.com/product/8809329229589.jpg'}
{'category': '생활용품', 'item_name': '씨앤)아이리버화이트', 'img_src': 'http://bgf-cu.xcache.kinxcdn.com/product/8809329229572.jpg'}
{'category': '생활용품', 'item_name': '바나실)소니이어폰화이트', 'img_src': 'http://bgf-cu.xcache.kinxcdn.com/product/4905524731668.jpg'}
{'category': '생활용품', 'item_name': '모나미)제브라3색볼펜', 'img_src': 'http://bgf-cu.xcache.kinxcdn.com/product/4901681321636.jpg'}
{'category': '생활용품', 'item_name': '오카)003알로에콘돔3입', 'img_src': 'http://bgf-cu.xcache.kinxcdn.com/product/4547691695215.jpg'}
{'category': '생활용품', 'item_name': '오카)003초박형콘돔3입', 'img_src': 'http://bgf-cu.xcache.kinxcdn.com/product/4547691676733.jpg'}
{'category': '생활용품', 'item_name': '스위트몬)담요', 'img_src': 'http://bgf-cu.xcache.kinxcdn.com/product/8809355827681.jpg'}
{'category': '생활용품', 'item

In [49]:
exists = os.path.isfile('./result_src.csv')

if exists:
    with open('./result_src.csv', 'a') as csvfile:
        fieldnames = ["category", "item_name", "img_src"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for i in range(len(result)):
            writer.writerow(result[i])
else:
    with open('./result_src.csv', 'w') as csvfile:
        fieldnames = ["category", "item_name", "img_src"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for i in range(len(result)):
            writer.writerow(result[i])

In [5]:
import pandas as pd
import random
csv_input = pd.read_csv('result.csv')
#csv_input['item_name']
table = csv_input.pivot(columns='item_name')

In [6]:
cs_index = []
for i in range(1000):
    cs_index.append(i+1)

In [7]:
table = pd.DataFrame(columns = csv_input['item_name'], index = cs_index)

In [8]:
table.shape

(1000, 2926)

In [9]:
table.iloc[0,0] = 1

In [14]:
for i in range(1000):
    for j in range(2926):
        num = int(random.randint(0,3))
        table.iloc[i,j] = num
        
        if(i % 50 == 0 and j % 50 == 0):
            print("i :", i,",j: ", j)

i : 0 ,j:  0
i : 0 ,j:  50
i : 0 ,j:  100
i : 0 ,j:  150
i : 0 ,j:  200
i : 0 ,j:  250
i : 0 ,j:  300
i : 0 ,j:  350
i : 0 ,j:  400
i : 0 ,j:  450
i : 0 ,j:  500
i : 0 ,j:  550
i : 0 ,j:  600
i : 0 ,j:  650
i : 0 ,j:  700
i : 0 ,j:  750
i : 0 ,j:  800
i : 0 ,j:  850
i : 0 ,j:  900
i : 0 ,j:  950
i : 0 ,j:  1000
i : 0 ,j:  1050
i : 0 ,j:  1100
i : 0 ,j:  1150
i : 0 ,j:  1200
i : 0 ,j:  1250
i : 0 ,j:  1300
i : 0 ,j:  1350
i : 0 ,j:  1400
i : 0 ,j:  1450
i : 0 ,j:  1500
i : 0 ,j:  1550
i : 0 ,j:  1600
i : 0 ,j:  1650
i : 0 ,j:  1700
i : 0 ,j:  1750
i : 0 ,j:  1800
i : 0 ,j:  1850
i : 0 ,j:  1900
i : 0 ,j:  1950
i : 0 ,j:  2000
i : 0 ,j:  2050
i : 0 ,j:  2100
i : 0 ,j:  2150
i : 0 ,j:  2200
i : 0 ,j:  2250
i : 0 ,j:  2300
i : 0 ,j:  2350
i : 0 ,j:  2400
i : 0 ,j:  2450
i : 0 ,j:  2500
i : 0 ,j:  2550
i : 0 ,j:  2600
i : 0 ,j:  2650
i : 0 ,j:  2700
i : 0 ,j:  2750
i : 0 ,j:  2800
i : 0 ,j:  2850
i : 0 ,j:  2900


KeyboardInterrupt: 

In [16]:
table.iloc[:40,]

item_name 주)제주빅간장치킨밥바 햄)매콤달콤치즈버거 주)매콤순살치킨빅밥바 도)팔도진미정식(전라) 주)스팸김치볶음밥  \
1                   2          0           3            2         3   
2                   0          2           2            3         2   
3                   0          1           0            1         3   
4                   3          2           2            1         1   
5                   2          3           0            2         1   
6                   0          3           0            2         2   
7                   1          2           1            2         0   
8                   2          1           3            2         3   
9                   0          0           1            3         0   
10                  0          0           3            2         1   
11                  1          2           2            1         1   
12                  1          1           3            3         1   
13                  2          2           3            3         3   
14                  1          1           2            3         2   
15                  0          1           3            2         0   
16                  0          1           3            2         1   
17                  1          3           3            1         2   
18                NaN        NaN         NaN          NaN       NaN   
19                NaN        NaN         NaN          NaN       NaN   
20                NaN        NaN         NaN          NaN       NaN   
21                NaN        NaN         NaN          NaN       NaN   
22                NaN        NaN         NaN          NaN       NaN   
23                NaN        NaN         NaN          NaN       NaN   
24                NaN        NaN         NaN          NaN       NaN   
25                NaN        NaN         NaN          NaN       NaN   
26                NaN        NaN         NaN          NaN       NaN   
27                NaN        NaN         NaN          NaN       NaN   
28                NaN        NaN         NaN          NaN       NaN   
29                NaN        NaN         NaN          NaN       NaN   
30                NaN        NaN         NaN          NaN       NaN   
31                NaN        NaN         NaN          NaN       NaN   
32                NaN        NaN         NaN          NaN       NaN   
33                NaN        NaN         NaN          NaN       NaN   
34                NaN        NaN         NaN          NaN       NaN   
35                NaN        NaN         NaN          NaN       NaN   
36                NaN        NaN         NaN          NaN       NaN   
37                NaN        NaN         NaN          NaN       NaN   
38                NaN        NaN         NaN          NaN       NaN   
39                NaN        NaN         NaN          NaN       NaN   
40                NaN        NaN         NaN          NaN       NaN   

item_name NEW맛있는핫도그오리지날(일부지역운영) 도)오늘의도시락 주)데리야끼꼬꼬닭 도)백종원삼겹살구이정식 햄)비프치즈버거  \
1                             0        0         3            1        1   
2                             0        2         2            1        3   
3                             3        2         3            0        0   
4                             0        0         3            0        0   
5                             2        0         1            0        2   
6                             0        1         0            3        1   
7                             2        0         0            3        0   
8                             2        1         0            3        0   
9                             0        2         3            1        2   
10                            1        1         1            0        3   
11                            0        2         3            3        3   
12                            3        3         1            1        2   
13                            0        1         3            3        2   
14                      

In [17]:
table.to_csv('result_ran.csv', index=True)

In [6]:
#import gauss
num = int(random.randint(0,100))
if num > 70:
    num = 0
print(num)

17


In [41]:
import numpy as np
for index, row in table.iterrows():
    rand_array = np.random.rand(1,2837)*10
    #gauss(0, 1)
    converted = rand_array.astype(int)
    row = converted
    print(converted)

[[0 9 1 ... 2 4 3]]
[[1 1 6 ... 0 4 1]]
[[8 1 1 ... 6 0 9]]
[[5 7 8 ... 9 4 3]]
[[9 2 9 ... 7 4 4]]
[[2 8 3 ... 7 5 9]]
[[0 4 6 ... 2 7 3]]
[[9 9 3 ... 1 6 0]]
[[0 4 8 ... 6 4 1]]
[[5 1 8 ... 9 3 4]]
[[6 1 6 ... 3 0 2]]
[[1 8 6 ... 0 7 2]]
[[0 6 0 ... 5 6 5]]
[[4 2 2 ... 3 2 4]]
[[0 4 8 ... 8 0 9]]
[[8 0 5 ... 1 3 2]]
[[8 2 4 ... 6 2 6]]
[[4 4 8 ... 8 3 2]]
[[0 7 3 ... 6 3 2]]
[[3 9 0 ... 9 3 7]]
[[3 2 7 ... 5 0 3]]
[[8 3 0 ... 2 8 1]]
[[3 1 3 ... 0 5 4]]
[[2 5 8 ... 4 6 3]]
[[3 7 1 ... 3 5 0]]
[[1 5 4 ... 2 2 8]]
[[5 9 0 ... 0 3 1]]
[[5 1 9 ... 1 1 8]]
[[6 9 9 ... 8 9 4]]
[[8 7 2 ... 6 6 9]]
[[4 2 9 ... 1 1 8]]
[[6 7 7 ... 2 0 2]]
[[0 6 5 ... 0 9 9]]
[[9 7 3 ... 7 0 6]]
[[3 5 3 ... 3 0 4]]
[[8 1 1 ... 8 2 9]]
[[9 6 3 ... 1 8 7]]
[[3 9 1 ... 4 1 5]]
[[6 5 9 ... 9 9 5]]
[[5 8 7 ... 7 3 0]]
[[1 1 3 ... 9 9 9]]
[[5 6 6 ... 0 1 9]]
[[4 3 8 ... 4 4 5]]
[[4 9 0 ... 9 8 3]]
[[2 7 5 ... 8 8 0]]
[[3 7 2 ... 5 9 4]]
[[7 8 2 ... 3 2 7]]
[[6 0 6 ... 0 5 7]]
[[8 9 8 ... 1 5 1]]
[[0 6 1 ... 1 2 2]]


[[5 3 2 ... 0 0 6]]
[[9 9 1 ... 8 7 1]]
[[7 9 3 ... 9 5 3]]
[[2 1 5 ... 0 6 3]]
[[2 1 4 ... 5 7 1]]
[[1 4 1 ... 2 3 1]]
[[9 7 7 ... 1 4 1]]
[[7 5 7 ... 9 1 6]]
[[5 4 2 ... 9 1 2]]
[[1 3 6 ... 3 3 1]]
[[8 1 7 ... 5 4 8]]
[[4 8 8 ... 1 3 1]]
[[8 0 3 ... 0 3 5]]
[[9 6 0 ... 2 9 3]]
[[2 1 7 ... 7 5 7]]
[[6 2 6 ... 9 2 6]]
[[3 3 7 ... 0 9 4]]
[[1 1 6 ... 0 2 8]]
[[6 8 2 ... 2 1 0]]
[[6 5 0 ... 3 3 0]]
[[0 1 5 ... 9 2 5]]
[[0 9 4 ... 6 9 0]]
[[5 4 9 ... 8 3 9]]
[[3 8 1 ... 7 9 0]]
[[8 1 9 ... 7 1 2]]
[[0 0 7 ... 1 3 3]]
[[6 9 7 ... 1 3 0]]
[[0 0 4 ... 2 7 0]]
[[1 2 3 ... 2 1 7]]
[[3 3 5 ... 4 9 6]]
[[9 2 5 ... 9 4 7]]
[[2 5 5 ... 4 2 3]]
[[2 3 5 ... 9 4 0]]
[[4 5 1 ... 9 5 5]]
[[6 4 0 ... 5 6 6]]
[[9 0 7 ... 4 0 3]]
[[1 7 3 ... 7 6 3]]
[[7 7 0 ... 9 8 3]]
[[4 0 0 ... 2 1 8]]
[[9 3 3 ... 9 9 7]]
[[3 2 5 ... 6 0 0]]
[[1 5 7 ... 4 3 4]]
[[0 2 3 ... 4 7 3]]
[[4 3 8 ... 8 5 6]]
[[9 8 3 ... 6 1 6]]
[[4 4 4 ... 7 2 1]]
[[3 1 5 ... 9 1 3]]
[[0 0 3 ... 7 3 9]]
[[0 5 4 ... 0 2 7]]
[[3 1 5 ... 5 7 7]]


[[8 1 1 ... 1 4 8]]
[[6 4 7 ... 4 7 9]]
[[5 1 0 ... 3 1 5]]
[[4 2 3 ... 5 0 3]]
[[8 0 2 ... 5 9 4]]
[[9 2 1 ... 0 4 3]]
[[7 4 8 ... 3 3 2]]
[[2 1 7 ... 1 8 0]]
[[7 6 6 ... 5 4 0]]
[[5 0 2 ... 9 6 0]]
[[5 1 1 ... 7 8 1]]
[[4 7 0 ... 1 3 3]]
[[0 9 6 ... 6 3 8]]
[[3 5 7 ... 6 4 1]]
[[6 7 8 ... 6 7 1]]
[[3 3 8 ... 6 0 0]]
[[1 6 7 ... 9 3 1]]
[[7 1 0 ... 8 8 6]]
[[9 7 0 ... 4 3 7]]
[[1 6 9 ... 8 1 5]]
[[7 4 2 ... 2 8 7]]
[[4 6 7 ... 9 8 8]]
[[1 9 5 ... 9 7 3]]
[[9 9 9 ... 6 2 3]]
[[6 9 8 ... 1 3 2]]
[[0 0 9 ... 2 9 0]]
[[1 4 0 ... 4 1 1]]
[[9 1 4 ... 3 2 5]]
[[2 3 7 ... 0 3 1]]
[[3 1 9 ... 8 2 4]]
[[4 0 1 ... 2 6 5]]
[[0 7 9 ... 5 0 7]]
[[6 5 5 ... 3 0 3]]
[[6 7 0 ... 3 3 3]]
[[7 5 8 ... 6 9 0]]
[[7 3 5 ... 8 1 8]]
[[2 8 6 ... 0 8 6]]
[[5 5 3 ... 7 6 7]]
[[2 3 5 ... 9 1 3]]
[[1 8 8 ... 7 8 7]]
[[6 8 8 ... 2 3 1]]
[[5 8 3 ... 0 0 9]]
[[6 8 0 ... 8 5 1]]
[[0 9 9 ... 7 6 9]]
[[3 4 4 ... 1 3 7]]
[[1 4 2 ... 2 4 6]]
[[9 0 0 ... 1 2 6]]
[[7 5 0 ... 8 1 4]]
[[5 6 6 ... 2 4 2]]
[[3 5 1 ... 7 2 9]]


[[9 7 4 ... 1 7 5]]
[[7 5 4 ... 7 9 1]]
[[5 5 1 ... 4 9 4]]
[[5 7 6 ... 5 6 0]]
[[6 0 8 ... 0 8 5]]
[[6 5 6 ... 0 3 6]]
[[3 2 3 ... 6 7 8]]
[[3 2 8 ... 8 0 8]]
[[5 5 3 ... 1 2 2]]
[[5 2 1 ... 3 0 5]]
[[5 2 0 ... 4 7 8]]
[[1 9 0 ... 1 1 0]]
[[9 2 8 ... 5 7 0]]
[[5 0 0 ... 0 5 5]]
[[5 1 2 ... 4 0 1]]
[[4 0 7 ... 5 0 5]]
[[6 9 5 ... 4 9 5]]
[[5 1 3 ... 0 4 2]]
[[5 6 3 ... 1 5 3]]
[[6 6 5 ... 2 8 7]]
[[6 9 1 ... 8 3 6]]
[[9 9 7 ... 1 8 0]]
[[5 2 9 ... 0 8 6]]
[[2 3 8 ... 1 4 1]]
[[3 4 3 ... 2 4 5]]
[[8 7 3 ... 1 8 2]]
[[5 6 2 ... 1 9 4]]
[[3 7 3 ... 9 8 8]]
[[3 0 6 ... 8 7 1]]
[[3 2 2 ... 3 3 5]]
[[0 7 8 ... 1 5 2]]
[[9 4 7 ... 1 8 0]]
[[6 2 3 ... 4 5 8]]
[[0 2 4 ... 4 3 6]]
[[5 8 1 ... 8 4 2]]
[[1 9 6 ... 7 5 2]]
[[5 6 8 ... 0 4 4]]
[[2 8 5 ... 5 3 4]]
[[1 9 8 ... 1 4 9]]
[[6 0 3 ... 4 3 4]]
[[8 1 9 ... 7 7 0]]
[[8 9 7 ... 0 4 3]]
[[9 6 9 ... 2 7 5]]
[[1 3 7 ... 0 1 0]]
[[2 1 3 ... 9 1 9]]
[[3 2 7 ... 4 0 8]]
[[3 2 8 ... 1 1 0]]
[[4 4 3 ... 5 6 5]]
[[1 2 7 ... 0 0 5]]
[[9 0 3 ... 9 6 7]]


[[0 2 3 ... 4 0 2]]
[[7 2 3 ... 2 2 1]]
[[6 3 3 ... 1 4 4]]
[[7 0 9 ... 6 6 5]]
[[6 7 1 ... 4 6 2]]
[[8 4 9 ... 4 0 3]]
[[1 4 2 ... 4 4 2]]
[[6 4 0 ... 1 7 6]]
[[5 6 7 ... 0 9 4]]
[[0 5 8 ... 3 3 9]]
[[9 6 6 ... 0 0 3]]
[[4 2 3 ... 2 7 8]]
[[0 4 6 ... 1 9 6]]
[[5 3 9 ... 2 6 9]]
[[3 7 7 ... 7 2 0]]
[[8 4 7 ... 2 6 7]]
[[6 5 3 ... 1 8 3]]
[[5 1 9 ... 5 6 0]]
[[3 5 2 ... 4 2 3]]
[[5 7 6 ... 7 8 7]]
[[6 5 2 ... 6 6 3]]
[[8 6 5 ... 1 3 4]]
[[5 5 9 ... 8 0 7]]
[[2 2 8 ... 2 2 1]]
[[9 1 2 ... 9 2 2]]
[[4 9 4 ... 6 9 8]]
[[1 1 6 ... 1 5 6]]
[[2 7 0 ... 0 4 6]]
[[3 6 8 ... 7 9 8]]
[[0 4 3 ... 6 5 7]]
[[9 3 8 ... 8 5 9]]
[[8 3 0 ... 3 7 3]]
[[4 0 9 ... 8 9 4]]
[[2 0 1 ... 4 3 9]]
[[5 3 8 ... 4 7 6]]
[[9 2 4 ... 4 6 3]]
[[0 1 6 ... 9 0 7]]
[[6 8 6 ... 7 0 2]]
[[6 7 1 ... 6 2 8]]
[[8 3 6 ... 7 1 4]]
[[1 1 9 ... 5 6 8]]
[[0 0 7 ... 9 9 0]]
[[0 2 1 ... 8 6 5]]
[[1 6 0 ... 5 7 7]]
[[3 1 4 ... 1 7 8]]
[[9 9 4 ... 1 6 3]]
[[8 1 6 ... 4 9 3]]
[[7 8 3 ... 5 0 9]]
[[7 5 4 ... 7 7 1]]
[[6 2 9 ... 5 3 1]]


In [36]:
table


category                                                        \
item_name      NaN 150투시팝캔디 1등급란6구 2080)메로나칫솔 2080)청은차치약칫솔세트 2080)치약칫솔세트   
0              NaN      NaN    NaN        NaN            NaN         NaN   
1              NaN      NaN    NaN        NaN            NaN         NaN   
2              NaN      NaN    NaN        NaN            NaN         NaN   
3              NaN      NaN    NaN        NaN            NaN         NaN   
4              NaN      NaN    NaN        NaN            NaN         NaN   
5              NaN      NaN    NaN        NaN            NaN         NaN   
6              NaN      NaN    NaN        NaN            NaN         NaN   
7              NaN      NaN    NaN        NaN            NaN         NaN   
8              NaN      NaN    NaN        NaN            NaN         NaN   
9              NaN      NaN    NaN        NaN            NaN         NaN   
10             NaN      NaN    NaN        NaN            NaN         NaN   
11             NaN      NaN    NaN        NaN            NaN         NaN   
12             NaN      NaN    NaN        NaN            NaN         NaN   
13             NaN      NaN    NaN        NaN            NaN         NaN   
14             NaN      NaN    NaN        NaN            NaN         NaN   
15             NaN      NaN    NaN        NaN            NaN         NaN   
16             NaN      NaN    NaN        NaN            NaN         NaN   
17             NaN      NaN    NaN        NaN            NaN         NaN   
18             NaN      NaN    NaN        NaN            NaN         NaN   
19             NaN      NaN    NaN        NaN            NaN         NaN   
20             NaN      NaN    NaN        NaN            NaN         NaN   
21             NaN      NaN    NaN        NaN            NaN         NaN   
22             NaN      NaN    NaN        NaN            NaN         NaN   
23             NaN      NaN    NaN        NaN            NaN         NaN   
24             NaN      NaN    NaN        NaN            NaN         NaN   
25             NaN      NaN    NaN        NaN            NaN         NaN   
26             NaN      NaN    NaN        NaN            NaN         NaN   
27             NaN      NaN    NaN        NaN            NaN         NaN   
28             NaN      NaN    NaN        NaN            NaN         NaN   
29             NaN      NaN    NaN        NaN            NaN         NaN   
...            ...      ...    ...        ...            ...         ...   
2896           NaN      NaN    NaN        NaN            NaN         NaN   
2897           NaN      NaN    NaN        NaN            NaN         NaN   
2898           NaN      NaN    NaN        NaN            NaN         NaN   
2899           NaN      NaN    NaN        NaN            NaN         NaN   
2900           NaN      NaN    NaN        NaN            NaN         NaN   
2901           NaN      NaN    NaN        NaN            NaN         NaN   
2902           NaN      NaN    NaN        NaN            NaN         NaN   
2903           NaN      NaN    NaN        NaN            NaN         NaN   
2904           NaN      NaN    NaN        NaN            NaN         NaN   
2905           NaN      NaN    NaN        NaN            NaN         NaN   
2906           NaN      NaN    NaN        NaN            NaN         NaN   
2907           NaN      NaN    NaN        NaN            NaN         NaN   
2908           NaN      NaN    NaN        NaN            NaN         NaN   
2909           NaN      NaN    NaN        NaN            NaN         NaN   
2910           NaN      NaN    NaN        NaN            NaN         NaN   
2911           NaN      NaN    NaN        NaN            NaN         NaN   
2912           NaN      NaN    NaN        NaN            NaN         NaN   
2913           NaN      NaN    NaN        NaN            NaN         NaN   
2914           NaN      NaN    NaN        NaN            NaN         NaN   
2915           NaN      NaN    NaN        NaN            N

In [ ]:
csv_cs = pd.read_csv('select_1.csv')
csv_cs

In [ ]:
csv_input['stock'] = random.randint(0,101)
csv_input.to_csv('result_ran.csv', index=True)